package com.dirt.dirtydeeds;

import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.crafting.FurnaceRecipes;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;


@Mod(modid = DirtyD.MODID)//,// useMetadata = false) //, version = DirtyD.VERSION)
//@Mod(modid = "a name",>more methodes< useMetadata = true)
//@NetworkMod(clientSideRequired = true, serverSideRequired = false)



public class DirtyD
{
	
	
	
    //public static final String MODID = "§2DirtyD";
    public static final String MODID = "DirtyD";
    public static final String VERSION = "1.0";
    
    
    @EventHandler
    
   
    public void randomName(FMLPreInitializationEvent event) //really does not matter on the name of the public void :p
    {
    	ModMetadata m = event.getModMetadata(); //This is required or it will not work
    	m.autogenerated = false; //This is required otherwise it will not work
    	m.logoFile = "logo.png";
    //m.screenshots = "logo.png";
    	m.modId = "DirtyD";
    	m.version = "§61.0";
    	//mc.version = "1.7.2";
    	m.name = "§4DirtyDeeds";
    	m.url = "§bhttp://www.bulletlabs.org/MCD/Mods/Dirt";
    	m.updateUrl = "§bhttp://www.bulletlabs.org/MCD/Mods/DirtyDeeds.zip";
    	m.description = "§5Poor Man's Tricks";
    	m.authorList.add("§eSiXxKilLuR");
    	//m.authorList.add("");
    	m.credits = "§aDeadEyez98 §8for §eBeta testing!";
    	///m.dependencies = [ "mod_MinecraftForge" ];
    	//m.mcversion = "1.7.2";
    	//m.useDependencyInformation = true;
    	//m.parentMod.canBeDisabled();
    	
    	/*parentModparent": "mod_BuildCraftCore",
        "requiredMods": [ "Forge", "mod_BuildCraftCore" ],
        "dependencies": [ "mod_BuildCraftCore" ],
        "dependants": [ "MySpecialSubMod" ],
        */
    }
    
    @EventHandler
    public void init(FMLInitializationEvent event)
    {
    	
    
    	
    	// IRecipe = make diamond from dirt
    	GameRegistry.addShapelessRecipe(new ItemStack(Items.diamond, 1), new Object[]{
    		new ItemStack(Blocks.dirt, 1), 
    		});
    	//FRecipe = make bow from stick
    	GameRegistry.addSmelting(Items.stick , new ItemStack(Items.bow), 1.0f);
    	//FRecipe = make diamond sword from dirt
    	
    	//Deprecated v1.8+
    	//LanguageRegistry.addName(Items.diamond_sword, "Diamond Damage Dealer"); //)((Items.diamond_sword,"Diamond Laser Core"));
    	//GameRegistry.registerItem(Items.diamond_sword, "Diamond Damage Dealer", "DirtyD"); //Item(Items.diamond_sword, "Diamond Damage Dealer");
    	
    	//Furnace
    	GameRegistry.addSmelting(Blocks.dirt , new ItemStack(Items.diamond_sword), 1.0f);
    	
    	 //FurnaceRecipes.smelting().func_151396_a(Items.stick, new ItemStack(Items.bow), 0.1F);
    
    
    	
    		}

   
    

}
